### ISSUE TITLE
Put cell moduli in input file `tube.in`

### ISSUE THREAD

**Issue by sbryngelson** [comp-physics/RBC3D#11]
It seems like the cell properties (type, moduli) should really be in `Input/tube.in` or something similar.

**Comment by suzm10** [comment]
Whoever does this should also add a way to select with cells to output to output to their own files in `tube.in`.

**Comment by sbryngelson** [comment]
@suzanmanasreh is this possible or no? it seems like it should be easy but maybe I'm missing a detail here. it would be nice to take such parameters out of the `.F90` files in the examples/cases.

**Comment by suzm10** [comment]
Yes, it technically would be easy to move `radEqv`, `nlat0`, `ES`, `ED`, `EB`, `vBkg`, etc.., and could potentially get rid of a few bugs (ex: if vBkg in `initcond` and `tube` don't match, the sim crashes). I saw someone else already do that in a fork. 

Ideally the `examples` would just be all inputs and the F90 code would be in some folder called `pre_process` or `launch_sim`, but there's no real one-size fits all for the place cell functionality, so if just a few things were moved, someone still has to change `initcond` to create a new case.

**Comment by sbryngelson** [comment]
It seems like the most reasonable solution is to move commonly used initial condition subroutines to the core `common` code, add the cell parameters to the input file, and make the `initcond.F90` files as minimal as possible such that basically no code is duplicated.

**Comment by suzm10** [comment]
Yeah that's probably necessary after my last change. One problem is knowing what cell to create for each celltype. I don't really want to hardcode celltype 1 as RBC, 2 as WBC, 3 as sickle cell, but it would probably be necessary to support this refactor or have some bit to set for each celltype if that celltype is a RBC and so on. Also, I think the restart procedure would have to be specified via input file if `tube` is taken out.

**Comment by suzm10** [comment]
wait i actually think having the components that make up the modulus values (wall shear rate, shear modulus in N/m, plasma viscosity, ...) would be more useful, so you can easily change shear rate and such like in other papers. i've been using this for all the cells (rbcs, wbcs, platelets), but sickle cells have their modulus values set arbitrarily, so i have no idea what to do about that

**Comment by sbryngelson** [comment]
how is that different from what i suggested

**Comment by suzm10** [comment]
shear rate and plasma viscosity aren't simulation parameters. they're used with equivalent radius to make the physical shear and bending modulus in N/m into dimensionless values for the simulation. i'm probably not going to complete this myself though, so it doesn't matter

**Comment by sbryngelson** [comment]
Yes this is intentional.

**Comment by suzm10** [comment]
why would that be intentional? it just makes it so i have to calculate more stuff

**Comment by sbryngelson** [comment]
The physics changes with the dimensionless parameters, not the dimensional ones. We often work hard to figure out the relevant dimensionless parameters that govern the physics of a flow, so that we can focus on changing _those_ parameters. 

Some famous examples of this are here: https://en.wikipedia.org/wiki/Dimensionless_numbers_in_fluid_mechanics

Though this idea applies broadly.

**Comment by suzm10** [comment]
I think a better description for this enhancement is moving duplicated example case functions to a common module but only doing the obvious ones that don't involve cell type parameters.
