### ISSUE TITLE
Viscosity Term

### ISSUE THREAD

**Issue by suzm10** [comp-physics/RBC3D#29]
The `viscRat` term can be set for a case in `Input/tube.in`. However, running a case with non-uniform viscosity (viscRat not 1) and walls causes the simulation to crash. This ticket is to fix it.

**Comment by suzm10** [comment]
if you set `deflate = .true.`, then `viscRat = 5` works

**Comment by suzm10** [comment]
Is running RBC's with a viscosity ratio = 5 (white) supposed to result in pretty much the same behavior as uniform viscosity (purple)? White ran for more timesteps on my mac

https://github.com/user-attachments/assets/add36fbe-6774-4ba4-804e-8f4cc64750bf

**Comment by sbryngelson** [comment]
The way to, in part, test this would probably be to run a case in a tube with ~20 blood cells or something and see if there is a visual difference.
