### ISSUE TITLE
Code runner to check compilation

### ISSUE THREAD

**Issue by suzm10** [comp-physics/RBC3D#30]
We shouldn't have to manually compile and run all cases before making a PR. This ticket is to create a code runner that we could submit jobs to to check that `/common` and all cases under `/examples/` compile. This would need an automated build script in `/.github/scripts/` to run on Phoenix or another cluster.

**Comment by suzm10** [comment]
Could someone who has access to MFC settings just show me what y'all did to get the phoenix runner to work? I need help. I also don't have access to settings here @sbryngelson to create a phoenix runner group.

**Comment by sbryngelson** [comment]
I can create a runner. Otherwise everything is in the `.github/` directory of MFC.

**Comment by suzm10** [comment]
Okay, I don't think I'll be able to test this on my fork if the runner is here, but maybe I can create a branch.

**Comment by sbryngelson** [comment]
The runner is in the default runner group, it should run so long as you specify self-hosted

**Comment by suzm10** [comment]
I do see it here, just not on my fork. Thank you for setting that up!

Hopefully, the workflow will be able to find the runner group now.

**Comment by sbryngelson** [comment]
@suzm10 this line in MFC: 

https://github.com/MFlowCode/MFC/blob/596ef8b6b5dd2b941c7a1027d3f30bdd2c217dd0/.github/workflows/test.yml#L110

is what prevents the self-hosted workflow from running on forks. You can remove it or submit a cursory PR that adds the normal self-hosted workflow without this to master, and then I think it might run on your forks. I may also need to adjust a setting or something, which I will look into right now. According to my GH options, 'Trusted' people should be able to auto-execute those CI runs.

Update: I made you a formal 'collaborator' (along with being part of the GitHub org). I think this might help (surely, with all the other above-enabled options, I think it will work, probably).

Update 2: Oh, I forgot, you also need to create a PR for your self-hosted jobs to run. It won't work without that, I'm pretty sure.

**Comment by suzm10** [comment]
Do you get an email about CI failing when I have a branch on the main repo for it? The job submission is working on the phoenix-runner branch, but not the full thing yet.

I tried removing the line on a [branch](https://github.com/suzm10/RBC3D/tree/testrunner) of my fork, but it still doesn't work because that runner isn't part of my fork. I'll see what creating a PR for this will do, but I think the best solution is me setting up an identical runner to yours on my fork.

<img width="935" alt="image" src="https://github.com/comp-physics/RBC3D/assets/75396711/c4ca4c74-5b13-4f27-9f66-45b309b4b1b8">

**Comment by sbryngelson** [comment]
this doesn't seem right and i do not recommend setting up your own runner. no I do not get an email about CI failing (or passing) and haven't (ever)

**Comment by suzm10** [comment]
Okay, I just submitted a PR to see if merging that to my fork will help, but if not, testing my workflow on a branch of this repo shouldn't be a big deal.

**Comment by suzm10** [comment]
Wait it says here that you can change which repos have access to a runner group in settings? Maybe you could add my fork.

<img width="755" alt="image" src="https://github.com/comp-physics/RBC3D/assets/75396711/28eea1be-3125-49ec-9f7f-f2872e8da9fa">

**Comment by sbryngelson** [comment]
your CI is running on the runner... it's just failing

**Comment by suzm10** [comment]
I think it's having a hard time with makedepf90 on the runner, and sbatch isn't working. I'll try to fix it.

Edit: The exact error is none of the mpi compilers working on there. I think your environment is using openmpi instead of mvapich2 even though mvapich2 is the one that's module loaded. I have no idea how to fix this.

**Comment by suzm10** [comment]
Can I get an ICE runner instead before I give up?

**Comment by sbryngelson** [comment]
do you want it to work on phoenix or ice?

**Comment by suzm10** [comment]
I just want it to compile, but I was hoping that seeing what happens on ICE would help rule out phoenix environment issues, so I just want the option to try both.

**Comment by sbryngelson** [comment]
ok i added one

[ice-1](https://github.com/comp-physics/RBC3D/settings/actions/runners/22) self-hosted Linux X64 ice

it has the keyword `ice`

**Comment by suzm10** [comment]
thanks everything's working a lot better on ice!! or at least closer to working

edit: successful ice compile: https://github.com/comp-physics/RBC3D/actions/runs/9503632036/job/26194491419

the one on phoenix is the exact same so the only thing that could be causing it to fail is bad environment paths.
